Labs/Lab4/module_1/models.py
class Teacher:
    def __init__(self, name, course, students={}):
        self.name = name
        self.course = course
        self.students = students

class Student:
    def __init__(self, id, first_name, last_name, gender):
        self.id = id
        self.first_name = first_name
        self.last_name = last_name
        self.gender = gender

Labs/Lab4/__init__.py
from module_1.views import mod as controllers
from flask import Flask

module_1 = Flask(__name__)
module_1.config.from_object('config')
module_1.register_blueprint(controllers)

Labs/Lab4/module_1/views.py
import datetime

from flask import Flask, session, request, redirect, url_for, render_template, make_response, Blueprint
from module_1.models import Teacher, Student
from module_1.serialize import deserialize, serialize

mod = Blueprint('module_1', __name__, url_prefix='')


@mod.route('/', methods=["GET"])
def index():
    teacher = retrieve_teacher()
    if teacher is None:
        # print("--------------------session is None")
        return redirect(url_for(".register"))
    return redirect(url_for(".show_students"))


@mod.route('/register', methods=["POST", "GET"])
def register():
    if request.method == 'GET':
        return render_template("module_1/register.html")
    else:
        name = request.form.get("name")
        course = request.form.get("course")
        teacher = Teacher(name, course)

        session["teacher"] = serialize(teacher)
        return redirect(url_for(".index"))


@mod.route('/student', methods=["GET"])
def show_students():
    teacher = retrieve_teacher()
    if teacher is None:
        return redirect(url_for(".register"))
    else:
        return render_template("module_1/students.html", students=teacher.students.values())


@mod.route('/add', methods=["POST", "GET"])
def add():
    if request.method == "GET":
        return  render_template("module_1/add.html")
    else:
        id = request.form.get("id")
        firstname = request.form.get("firstname")
        lastname = request.form.get("lastname")
        gender = request.form.get("gender")
        teacher = retrieve_teacher()
        teacher.students[id] = Student(id, firstname, lastname, gender)
        session['teacher'] = serialize(teacher)
        return redirect(url_for(".show_students"))


@mod.route('/delete/<id>', methods=["POST", "GET", "DELETE"])
def delete(id):
    teacher = retrieve_teacher()
    teacher.students.pop(id)
    session["teacher"] = serialize(teacher)
    return redirect(url_for(".show_students"))


@mod.route('/edit/<id>', methods=["POST", "GET"])
def edit(id):
    teacher = retrieve_teacher()
    student = teacher.students.pop(id)
    if request.method == "GET":
        return render_template("module_1/edit.html", student=student)
    else:
        student.first_name = request.form.get("firstname")
        student.last_name = request.form.get("lastname")
        student.gender = request.form.get("gender")

        teacher.students[id] = student
        session["teacher"] = serialize(teacher)
        return redirect(url_for(".show_students"))


'''
The function stores the information of a teacher into a cookie
'''
@mod.route('/save')
def save():
    serialized_teacher = session.get("teacher")
    resp = make_response(render_template("module_1/save.html"))
    if serialized_teacher is not None:
        expire_date = datetime.datetime.now() + datetime.timedelta(days=90)
        resp.set_cookie("_teacher", serialized_teacher, expires=expire_date)

    return resp


'''
checks whether or not a teacher object exists in the session.
If not, the function shows the register page
'''
def retrieve_teacher():
    serialized_teacher = session.get("teacher")
    if serialized_teacher is None:
        serialized_teacher = request.cookies.get('teacher')
    if serialized_teacher is not None:
        # print('got session')
        return deserialize(serialized_teacher)
    return None

Labs/Lab4/templates/module_1/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add</title>
</head>
<body>

<form method="post" action="{{ url_for('module_1.add') }}">
    <table>
        <tr>
            <td>Id</td>
            <td><input type="number" name="id"></td>
        </tr>
        <tr>
            <td>First name</td>
            <td><input type="text" name="firstname"></td>
        </tr>
        <tr>
            <td>Last name</td>
            <td><input type="text" name="lastname"></td>
        </tr>
        <tr>
            <td>Gender</td>
            <td>
                <select name="gender">
                    <option value="Male">Male</option>
                    <option value="Female">Female</option>
                </select>
            </td>
        </tr>
        <input type="submit" value="Add"/>
    </table>
</form>


</body>
</html>

Labs/Lab4/templates/module_1/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit</title>
</head>
<body>
<div class="center">

<form method="post" action="{{ url_for('module_1.edit', id=student.id) }}">
    <table>
        <tr>
            <td>Id</td>
            <td>{{ student.id }}</td>
        </tr>
        <tr>
            <td>First name</td>
            <td><input type="text" name="firstname" value="{{ student.first_name }}"></td>
        </tr>
        <tr>
            <td>Last name</td>
            <td><input type="text" name="lastname" value="{{ student.last_name }}"></td>
        </tr>
        <tr>
            <td>Gender</td>
            <td>
                <select name="gender">
                    <option value="Male">Male</option>
                    <option value="Female" {{ "selected" if student.gender == 'FEMALE' }}>Female</option>
                </select>
            </td>
        </tr>
        <input type="submit" value="Done"/>
    </table>
</form>
</div>
</body>
</html>

Labs/Lab4/templates/module_1/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
</head>
<body>

<form method="post" action="{{ url_for('module_1.register') }}">
    <table>
        <tr>
            <td>Name</td>
            <td><input type="text" name="name"></td>
        </tr>
        <tr>
            <td>Course</td>
            <td><input type="text" name="course"></td>
        </tr>

        <input type="submit" value="Submit"/>
    </table>
</form>

</body>
</html>

Labs/Lab4/templates/module_1/save.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Save</title>
</head>
<body>
    <a href='{{url_for("module_1.show_students")}}' >Return to the students page</a>
</body>
</html>

Labs/Lab4/templates/module_1/students.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Students List</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"></script>
</head>
<body>

<div class="panel panel-default">
    <div class="panel-heading">Student List</div>
    <div class="table-responsive">
        <table class="table table table-hover">
            <thead>
            <tr>
                <th></th>
                <th></th>
                <th>ID</th>
                <th>Gender</th>
                <th>First Name</th>
                <th class="col-md-10">Last Name</th>
            </tr>
            </thead>
            {% for s in students: %}
            <tr>
                <td><a href="{{url_for('module_1.edit', id= s.id)}}"><i class="fa fa-pencil-square-o"></i></a></td>
                <td><a href="{{url_for('module_1.delete', id =s.id)}}"><i class="fa fa-times"></i></a></td>
                <td>{{s.id}}</td>
                <td><i class="{{'fa fa-mars' if s.gender == 'MALE' or s.gender == 'Male' else 'fa fa-venus'}}"></i>
                <td>{{s.first_name}}</td>
                <td>{{s.last_name}}</td>
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>

<a class="btn btn-success" href="{{url_for('module_1.add')}}"><i class="fa fa-venus-mars" aria-hidden="true"></i> New</a>
<a class="btn btn-primary " href="{{url_for('module_1.save')}}"><i class="fa fa-floppy-o" aria-hidden="true"></i> Save</a>

</body>
</html>